services:
  backend:
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.backend.loadbalancer.server.port=4000"
    networks:
      - traefik_network

  frontend:
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    networks:
      - traefik_network

  reverse-proxy:
    image: traefik:v3.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt
    networks:
      - traefik_network

volumes:
  letsencrypt:

networks:
  traefik_network:
