services:
  backend:
    image: gchr.io/your-repo/backend:latest  # Replace with your actual image
    labels:
      - "traefik.http.routers.backend.rule=Host(`api.gub.town`)"
      - "traefik.http.routers.backend.entrypoints=appsecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info

  frontend:
    image: gchr.io/your-repo/frontend:latest  # Replace with your actual image
    labels:
      - "traefik.http.routers.frontend.rule=Host(`gub.town`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: '0.3'
          memory: 300M
    environment:
      - NODE_ENV=production

  reverse-proxy:
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--entrypoints.appsecure.address=:4000"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=your-email@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - 443:443
      - 80:80
      - 4000:4000
    restart: always
